"""empty message

Revision ID: 490b86979ca8
Revises: 5165c9b26daa
Create Date: 2022-05-05 07:52:09.010905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '490b86979ca8'
down_revision = '5165c9b26daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'orders_status', ['type'])
    op.alter_column('payments', 'order_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'order_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint(None, 'orders_status', type_='unique')
    # ### end Alembic commands ###
