"""empty message

Revision ID: 5165c9b26daa
Revises: 54e1fcbe9d81
Create Date: 2022-05-05 06:24:36.779662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5165c9b26daa'
down_revision = '54e1fcbe9d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_status_type_key', 'orders_status', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_status_type_key', 'orders_status', ['type'])
    # ### end Alembic commands ###
