"""empty message

Revision ID: 54e1fcbe9d81
Revises: 93e14a8d8e4d
Create Date: 2022-05-05 04:27:48.855717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '54e1fcbe9d81'
down_revision = '93e14a8d8e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'order_id')
    # ### end Alembic commands ###
