"""empty message

Revision ID: 93e14a8d8e4d
Revises: acf65b1e5070
Create Date: 2022-05-05 04:10:54.955823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e14a8d8e4d'
down_revision = 'acf65b1e5070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantityStock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'quantityStock')
    # ### end Alembic commands ###
