"""empty message

Revision ID: acf65b1e5070
Revises: 27784998b921
Create Date: 2022-05-05 03:56:53.252655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acf65b1e5070'
down_revision = '27784998b921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('mercadopago_id', sa.String(length=60), nullable=True),
    sa.Column('mercadopago_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mercadopago_id')
    )
    op.drop_table('payment_model')
    op.alter_column('orders', 'status_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('orders', 'payment_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'payment_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('orders', 'status_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_table('payment_model',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mercadopago_id', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('mercadopago_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_model_pkey'),
    sa.UniqueConstraint('mercadopago_id', name='payment_model_mercadopago_id_key')
    )
    op.drop_table('payments')
    # ### end Alembic commands ###
