"""empty message

Revision ID: b9b897d2a517
Revises: 4760b8a2e62b
Create Date: 2022-05-04 12:41:33.448332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9b897d2a517'
down_revision = '4760b8a2e62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts_products', 'cart_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('carts_products', 'product_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts_products', 'product_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('carts_products', 'cart_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
